# -*- coding: utf-8 -*-
"""formateur_numerique.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rtSMO5uf_CwJI5RDuoS9VpIA8Hi-kaa6

# Ma premiere commande python
## Salut World
"""

print("Hello")
