@startmindmap
'https://plantuml.com/mindmap-diagram
!theme carbon-gray

title AGENT(E) DE SÛRETE ET DE SECURITE PRIVEE (A2SP)


*[#FFBBCC]: A2SP
Agent(e) de surete et de securité privee;

'left side

** ADS (Sureté)

'right side

** SSIAP 1 (Sécurité incendie)
***[#orange] SST
***[#lightblue] H0BO
***[#red] Service de sécurité incendie


@endmindmap

