= A2SP - AGENT(E) DE SÛRETE ET DE SECURITE PRIVEE

== 1) Thème et titre
A2SP = ADS + SSIAP 1 + SST + H0B0 +
Agent de sécurité incendie, au titre de SSIAP niveau 1 (Service de Sécurité Incendie et d'Assistance aux Personnes) et agent de sureté.


// == ADS
// == SST
// == H0BO
// == SSIAP 1

== 2) Description présentation
// == Métier de SSIAP 1 et la Complémentarité Sécurité Incendie et Sûreté

// Le métier de SSIAP 1 (Service de Sécurité Incendie et d'Assistance à Personnes de niveau 1) est

Le poste central de sécurité ou PCS, est le lieux essentiel dans le secteur de la sécurité incendie, +
où il s'agit de prévenir et de gérer les risques liés aux incendies dans les établissements recevant du public. +
Cependant, dans le PCS il y a également des préoccupations de sûreté, contribuant ainsi à la sécurité globale de ces lieux.

La certification SSIAP 1 et ADS sont une base solide pour aborder la question de la sûreté. Les professionnels de SSIAP 1 sont formés à identifier les situations potentiellement dangereuses, à gérer les accès aux bâtiments, à surveiller les systèmes de sécurité, et à coopérer avec les forces de l'ordre en cas de menaces ou d'incidents liés à la sûreté. Ils assurent la protection des personnes, des biens, et des informations sensibles.

L'un des avantages majeurs de la complémentarité entre la sécurité incendie et la sûreté réside dans la capacité à gérer de manière proactive +
et intégrée les risques. Les agent A2SP sont formés pour réagir efficacement en cas d'incendie, +
mais ils peuvent également contribuer à la prévention des actes malveillants et des situations d'urgence liées à la sûreté. +
En intégrant ces deux domaines de la sécurité, les établissements assurent une protection plus globale et renforcent la sécurité de leurs occupants.

Les évolutions professionnelles possibles pour les titulaires de la certification SSIAP 1 incluent non seulement des avancements dans la sécurité incendie, +
mais aussi des opportunités de carrière dans le domaine de la sûreté, comme la sécurité privée, la gestion de crise, ou la prévention des risques liés aux menaces. +
La polyvalence de ces professionnels les rend précieux pour les employeurs soucieux de garantir une sécurité complète.

En somme, l'A2SP est au cœur de la sécurité incendie, mais il embrasse également les préoccupations de sûreté, +
offrant ainsi une approche intégrée de la protection des personnes et des biens. +
Cette complémentarité renforce la sécurité des établissements et ouvre des opportunités professionnelles diverses pour les spécialistes de la sécurité, de la maintenances des outils incendies, télésurveillance.

== 3) Public

être apte physiquement, cette aptitude étant attestée par un certificat médical datant de moins de trois mois, conformément à l'annexe VII de l'arrêté du 02 mai 2005.
Effectif entre 10 et 20 apprenants


== 4) Objectifs pédagogiques

// listes des compétences par domaines de compétence

.Missions de l’agent SSIAP1
* La prévention des incendies
* La sensibilisation des employés en matière de sécurité contre l’incendie, et d’assistance à personnes
* L’entretien élémentaire des moyens concourant à la sécurité incendie
* L’alerte et l’accueil des secours
* L’évacuation du public
* L’intervention précoce fasse aux incendies
* L’assistance à personnes au sein des établissements ou ils exercent
* L’exploitation du PC de sécurité incendie

== 5) Compétences visés(objectifs opérationnels)

* Effectuer l'entretien et et les vérifications élémentaires des installations et équipements de sécurité
* Appliquer des consignes de sécurité
* Lire et manipuler des tableaux de signalisation
* Effectuer des rondes de sécurité et surveillance des travaux
* Assurer la surveillance au PC
* Passer des appels et réceptionner les services publics de secours
* Pratiquer le secours à victimes
* Porter assistance à personnes
* Mettre en œuvre des moyens de secours et de mise en sécurité


== 6) Durée/Temporisation

.Durée de la formation : 140h
* SSIAP 1 : 70 heures + examen
* ADS : 35 heures + examen

.Deux formules possibles:
* présentiel complet (9h/12-13h/17h)
* hybridation présentiel/distanciel (9h/12-13h/17h) :
** 50% e-learning
** 50% en centre de formation

== 7) Moyen d’accompagnement/Suivis pédagogique
