= Scénario pédagogique global (SPG): A2SP - AGENT(E) DE SÛRETE ET DE SECURITE PRIVEE

reference: link:https://www.afpa.fr/formation-qualifiante/agent-de-surete-et-de-securite-privee[A2SP AFPA]

== 1) Thème et titre
titre: A2SP, Agent de sécurité incendie, au titre de SSIAP niveau 1 et agent de sureté. +

* SSIAP 1 = Service de Sécurité Incendie et d’Assistance à Personnes niveau 1 +
* ADS = agent de sécurité
* SST = sauveteur secouriste du travail
* BS-BE manoeuvre = Interventions élémentaires et/ou des manœuvres d’ordre électrique en basse tension dans un environnement présentant des risques électriques.
* A2SP = ADS + SSIAP 1 + SST + BS-BE manoeuvre

== 2) Description présentation

La sécurité indendie agit à prévenir et gérer les risques liés aux incendies dans les établissements recevant du public. +
cette mission est piloté depuis le PCS(poste centrale de sécurité) ou il y a également des préoccupations de sûreté, contribuant ainsi à la sécurité globale de ces lieux.

La certification SSIAP 1 et ADS sont une base solide pour aborder la question de la sûreté. Les professionnels de SSIAP 1 sont formés à identifier les situations potentiellement dangereuses, à gérer les accès aux bâtiments, à surveiller les systèmes de sécurité, et à coopérer avec les forces de l'ordre en cas de menaces ou d'incidents liés à la sûreté. Ils assurent la protection des personnes, des biens, et des informations sensibles.

L'un des avantages majeurs de la complémentarité entre la sécurité incendie et la sûreté réside dans la capacité à gérer de manière proactive +
et intégrée les risques. Les agent A2SP sont formés pour réagir efficacement en cas d'incendie, +
mais ils peuvent également contribuer à la prévention des actes malveillants et des situations d'urgence liées à la sûreté. +
En intégrant ces deux domaines de la sécurité, les établissements assurent une protection plus globale et renforcent la sécurité de leurs occupants.

Les évolutions professionnelles possibles pour les titulaires de la certification SSIAP 1 incluent non seulement des avancements dans la sécurité incendie, +
mais aussi des opportunités de carrière dans le domaine de la sûreté, comme la sécurité privée, la gestion de crise, ou la prévention des risques liés aux menaces. +
La polyvalence de ces professionnels les rend précieux pour les employeurs soucieux de garantir une sécurité complète.

Le titre A2SP est au cœur de la sécurité incendie, mais il embrasse également les préoccupations de sûreté, +
offrant ainsi une approche intégrée de la protection des personnes et des biens. +
Cette complémentarité renforce la sécurité des établissements et ouvre des opportunités professionnelles diverses pour les spécialistes de la sécurité, de la maintenances des outils incendies, télésurveillance.

== 3) Public

. Maîtriser la langue française est indispensable, à l'oral et à l'écrit, pour la
compréhension et pour l'expression. Un résultat de niveau B1 au CECRL est requis.
Pour les ressortissants d'un Etat membre de l'Union européenne ou d'un Etat partie à
l'accord sur l'Espace économique européen ou les ressortissants d'un pays tiers, ils
doivent justifier d'un niveau de maîtrise de la langue française tel spécifié dans l'arrêté du
31 mars 2022.
. Présenter une autorisation préalable d’accès à la formation délivrée par le CNAPS (pour
laquelle les ressortissants étrangers non européens doivent justifier de 5 années de
résidence continue et régulière sur le territoire, attestées par un ou plusieurs titres de
séjour.) L’autorisation est matérialisée par un numéro personnel.
. Justifier de son aptitude physique attestée par un certificat médical de moins de 3 mois
pour pouvoir se former et se présenter au SSIAP 1.
Nota bene : Il est possible de bénéficier d’une adaptation de parcours si :
* Le candidat est titulaire du SST, en cours de validité
* Le candidat est détenteur d’un avis de formation initiale ou attestation de formation de
recyclage du BS-BE manoeuvre,
* Le candidat est détenteur du diplôme SSIAP 1, en cours de validité, et si nécessaire, des
attestations de recyclage ou de remise à niveau.

Effectif entre 10 et 20 apprenants

== 4) Objectifs pédagogiques

// listes des compétences par domaines de compétence

.Missions de l’agent SSIAP1
* La prévention des incendies
* La sensibilisation des employés en matière de sécurité contre l’incendie, et d’assistance à personnes
* L’entretien élémentaire des moyens concourant à la sécurité incendie
* L’alerte et l’accueil des secours
* L’évacuation du public
* L’intervention précoce fasse aux incendies
* L’assistance à personnes au sein des établissements ou ils exercent
* L’exploitation du PC de sécurité incendie
// a réécrire avec taxonomie de bloum

== 6) Compétences visés(objectifs opérationnels)

// Elles peuvent se passer de la taxonomie de bloum
* Effectuer l'entretien et et les vérifications élémentaires des installations et équipements de sécurité
* Appliquer des consignes de sécurité
* Lire et manipuler des tableaux de signalisation
* Effectuer des rondes de sécurité et surveillance des travaux
* Assurer la surveillance au PC
* Passer des appels et réceptionner les services publics de secours
* Pratiquer le secours à victimes
* Porter assistance à personnes
* Mettre en œuvre des moyens de secours et de mise en sécurité


== 6) Durée/Temporisation

.Durée de la formation : 140h
* SSIAP 1 : 70 heures + examen
* ADS : 35 heures + examen

.Deux formules possibles:
* présentiel complet (9h/12-13h/17h)
* hybridation présentiel/distanciel (9h/12-13h/17h) :
** 50% e-learning async
** 50% en centre de formation

== 7) Moyen d’accompagnement/Suivis pédagogique

détails de l'organisation des journées sur les differents formule pour dispenser la formation

planning jours bloc de competences
mode de communication



Présentation :
Faire une phrase en plus pour introduire la surete et la securité
Remonter la description du métier plus haut et parler des certifications qui composent les compétences dans le programme plus bas
Parler de la complémentarité pas que des compétences mais des certifications sur le marché du travail

on ne fait pas 9) Programme pédagogique : contenu et séquencement