= Scénario pédagogique global (SPG)

Les critères qui font un scénario pédagogique globale :

== Thème (Qualiopi) :
on dissocie le thème qui est au global dans laquelle s'insère la formation, le thème n’est pas la formation mais le sujet général dans lequel il s'insère.

== Titre (Qualiopi) :
* La formulation du titre, elle reprends soit le titre d’un métier ou d’une posture professionnelle, ou bien un titre qui reprends la formulation d’un objectif pédagogique, commençant par un verbe d’action et un contexte professionnelle d’application, si on garde la notion de phrases génériques (les fondamentaux de l'élevage de poulet), on doit donner des éléments de contextes précisant le pourquoi et le comment de la formation pour être suffisamment spécifique

== Introduction : Présenter et Décrire
* L’objectif est de donner des tendances sur le mood de la formation, l’orientation et le parti pris, c’est comme une bande-annonce avec une introduction sur le secteur d’activité ou le domaine d’application, la description, c'est la deuxième partie de l’introduction, où il est question de présenter en détail l’articulation, le fonctionnement de la formation ou les grandes thématiques abordées dans la formation

== Public (Qualiopi) :
* Cible privilégiée pour les personnes amenées à suivre la formation, on ne donne pas de restriction sur les situations des personnes et sur les commanditaires, on va donner des critères d’expériences, d’objectif professionnelles, parfois d’âges, etc
* On précise le nombre de personnes minimum et maximum par session de formation

== Pré-requis et conditions d’accès à la formation (Qualiopi) :
* Il faut préciser de manière spécifique les conditions minimales à maîtriser ou posséder : diplômes, âges, expériences,
* Le pré-requis ne concerne que la situation de la personne au moment de son entrée en formation, elle n’est pas dépendante de son évolution dans la formation (sur le plan pédagogique)

== Objectifs pédagogiques (Qualiopi) et
== Compétences visés (Qualiopi) :

* Référentiel emploi et activités : document qui décrit l’ensemble des différentes missions types d’un emploi en particulier

* Référentiel formation : document qui présente la transformation d’un ensemble d’activités en compétences professionnelles à développer en formation

* Scénario pédagogique globale (SPG) ou Fiche formation/programme : déclinaison du référentiel formation en proposition pédagogique avec une ingénierie pédagogique adapté à un public spécifique

* L’objectif pédagogique est une formulation explicite des savoir, savoir-faire et les savoir-être qui sont attendus à l’issue de la formation

** On utilisera toujours la Taxonomie de Bloom pour formaliser un objectif pédagogique

* Compétence visée ou objectif opérationnel ou objectif de formation :
_l’ensemble des acquis issus de la formation qui sont mobilisables en une situation professionnelle contextualisée_

** On reprend une formulation plus globale qu’un objectif pédagogique d’une sous-compétence, soit la formulation d’un bloc de compétences ou domaines d’activités
** Il vise l’insertion des objectifs pédagogiques avec une application professionnelle, parfois on va juste reprendre les termes du commanditaire, la Taxonomie de Bloom peut-être utilisé, mais elle n’a pas de caractère obligatoire
* Ex 1 : “Analyser la situation financière d’une entreprise” est un objectif pédagogique mais qui est tellement large qu’il faut plusieurs savoir, savoir-faire et savoir-être pour mener à bien cette action sous forme de compétence. Cet objectif pédagogique pourrait être un bloc de compétences. On va la décomposer en plusieurs autres sous-objectif pédagogiques pour être plus précis dans les savoirs nécessaires, par exemple “Identifier les éléments clefs dans un bilan et un résultat comptable”, “Lister l’ensemble des critères de la Norme X pour vérifier la bonne tenu des comptes”, (ces exemples de compétences ne sont pas véritables, il s’agit d’un exemple de décomposition).
* Ex 2 : Concevoir une stratégie marketing adapté à un public cible (Bloc de compétences) :
Définir le produit/service du public cible (objectif pédagogique et compétences à part entière)
Concevoir des personas (clients types) du public cible
Réaliser une enquête des besoins du public cible sur le produit/service
Illustrer les exemples d’usages par des vidéos et des photos sur un format publicitaire
Diffuser les publicités sur les différents canaux de communication
Suivre la performance des publicités sur les canaux de communication en adaptant en fonction des réactions sur les réseaux sociaux


Durée (Temporisation) (Qualiopi) :
La durée, c’est le temps total de formation en journée (rappel : une journée = 7h) et en heure (obligatoire)
La temporisation, il n’est pas nécessaire de marquer Temporisation dans le titre de votre partie, il est plutôt important dans la durée de préciser les répartitions en volumes horaires si il y a des temps dissociés, des stages, de l’alternance, etc (mentionné parfois)

Moyen d’accompagnement et Suivi pédagogique (Qualiopi) :
Nommer les acteurs accompagnant l’apprenant durant la formation : responsable pédagogique, référent handicap, formateurs, coordinateur pédagogique, technicien de production éventuel, etc en précisant les contacts professionnels
Donner les éléments de suivis : réunion ponctuelle, points de rdv collectif, les temps d’échanges spécifiques, système d’email ou de ticket de suivi, hotline téléphonique, émargements, plateforme intranet (pas elearning mais administrative), etc
Suivi pédagogique -> Organisation formatif : dans la formation, comment est organisé la répartition des différents temps, ce n’est pas seulement les interlocuteurs ou les temps d’échanges formelles, mais c’est l’organisation durant le temps de formation
Ex : suivi par le formateur sur les temps de cours, disponibilité pour des échanges sur RDV à propos des cours ou des projets, existence de coach ou de tuteur et temps dédié à ce suivi

Programme pédagogique (Modalités pédagogiques) (Qualiopi) : du contenu et du séquencement

Modalités pédagogiques/Motif pédagogique : Modalité = quel action / Motif = quel rythme, un rythme dans le découpage théorique, pratique et évaluatif qui se répète dans la formation et dans le temps en s’adaptant aux différents thèmes, on présente son style pédagogique en décrivant un motif pédagogique (pas obligatoire). On précise ce qui est en présentiel, et distanciel, avec une plateforme e-learning, avec des machines ou des outils en présentiel (de manière synthétique).
Pour les modules plus ou moins courts (plus ou moins 10j mais ce n’est pas un absolu), Il reprend pour chaque module/séance, la répartition des modalités dans l’ordre d’apparition et précise sa nature et sa durée

Thématique
Sujet
Modalité
Durée
Management
Découverte de la notion de management agile
Présentation avec un support
60 min
Management
Les avantages/inconvénients de l’agilité
Débat collectif avec rédaction d’un rapport individuel
90 min
Management
Temps d’évaluations
QCM de 40 questions
30 min

(La forme du tableau est conseillé mais pas obligatoire)


Pour les formations longues, plusieurs mois, le programme est découpé dans le temps, compétences par compétences est une excellente idée en précisant le type de contenu au fur et à mesure, il est aussi possible de faire le programme thème par thème au delà du découpage par compétence, on peut donner un niveau de détail qui précise les grandes lignes sans avoir forcément le découpage par séquence et par séance
Pour les blocs à découper en Module, Séquence et Séance : on parle du SPD, qui est à utiliser lorsque le programme est beaucoup trop long (pas obligatoire au niveau du SPG)
Module : réponds à un bloc de compétences (1BC = 1 ou plusieurs modules)
Séquence : réponds à une sous-compétence ou compétences clefs (1 compétence = plusieurs séquences)
Séance : est un sous ensemble d’une séquence
Le SPD n’est qu’un document qui détaille l’articulation entre les modules, les séquences et les séances. On précise l’organisation pédagogique et notamment les évaluations (ingénierie pédagogique et ingénierie d’éval/certification)

Modalités d’évaluations (Qualiopi) :
Le recueil des besoins en début de formation et l’évaluation diagnostique : il est nécessaire pour comprendre les attentes mais aussi les acquis de manière précise, c’est un gros test réalisé en général en amont du recrutement dont on doit tenir
On précise les différentes évaluations, leurs sens et ce qui sera évalué, pour permettre à chacun de comprendre le parcours évaluatif de la formation en précisant ce qui vient ou non dans un objectif de certification

Modalités de certification et Certification visé (Qualiopi) :
Modalités de certification : L’ensemble des critères évaluations et hors évaluations qui sont nécessaire à l’obtention de la certification
Certification visé : On explique le lien avec la certification ou les certifications qui composent la formation, préciser la nature de la certification (RNCP, autres certificateurs, etc), le nom précis et complet, le numéro de délivrance (RNCP), la date de validité/publication (RNCP)  et la date de publication du décret sur l’avis de France Compétences sur le diplôme (RNCP), le propriétaire de la certification.


 Lieux (Qualiopi) :
Si présentiel : adresse et modalités d’accès au lieu
Si elearning : Nom de la plateforme et conditions d’accès informatique

Tarifs :
Avec et sans TVA ou TVA appliquée
On privilégie les modalités de paiements sur le contrat ou CGV


 Moyens logistique et matériels (Qualiopi) :
Matériel requis pour la formation, prêté en formation, disponible en formation
Configuration minimal pour travailler en formation : configuration d’un ordinateur, d’un logiciel, etc
Liste des éléments éventuels à acheter en précisant achat collectif possible ou non et obligation ou non de ce matériel


 Poursuite en formation (Qualiopi) :
Les évolutions en terme de spécialisation ou de diversification après la formation, lien vers des écoles ou des diplômes

 Délais d’accès (Réglementaire) :
Durée de mise à disposition par le CF ou le Formateur de la formation, le dispositif légale impose 14 jours de délai minimum

 Accessibilité et Handicap (Qualiopi) :
Préciser qu’un référent handicap est disponible pour écouter les besoins spécifiques et prévoir les adaptations en formation ou l’orientation possible selon la situation de chaque apprenant avec le responsable formation et les formateurs

 Témoignage Evaluation de la formation (Qualiopi) :
A la fin de chaque formation, un questionnaire de satisfaction est envoyé à la fin du dernier jour (à chaud) et 3 à 6 mois plus tard (à froid)
Les statistiques de satisfaction et le taux de réussite des certifications sont à présenter pour chaque formation

Témoignage apprenants/commanditaires :
Listes des clients éventuels et des témoignages comme gage de qualité


