= ECF(Evaluation en Cour de Formation) SSIAP1

== 1) Thème et titre
Agent de sécurité incendie, au titre de SSIAP niveau 1 (Service de Sécurité Incendie et d'Assistance aux Personnes)

== 2) Description présentation

Tout établissement recevant du public ou des travailleurs à légalement l'obligation d'assurer sa sécurité incendie. +
Le service de sécurité incendie localisé au PCS(poste central de sécurité) est formé l'équipe de SSIAP(Service de Sécurité Incendie et d'Assistance à Personnes).
Cette équipe est composé d'agents et chef d'équipe. +
Ils sont responsables de la prévention des incendies et de la sécurité incendie au sein de l'établissement. +

L'équipe SSIAP 1 est essentielle pour effectuer des rondes de sécurité, surveiller les équipements de sécurité, intervenir en cas d'incendie, +
et évacuer les personnes en cas d'urgence. +
Ils assurent également la liaison avec les services d'incendie et de secours. +

Les évolutions professionnelles possibles pour les titulaires de la certification SSIAP 1 incluent la progression +
vers des niveaux supérieurs tels que SSIAP 2 et SSIAP 3, avec des responsabilités et des tâches accrues en matière +
de sécurité incendie. +
Certains peuvent également choisir de se spécialiser dans des domaines connexes tels que la sécurité privée, +
la gestion de crise, ou la prévention des risques, ainsi que des opportunités d'avancement et +
de spécialisation dans le domaine de la sécurité incendie.


link:https://www.afpa.fr/formation-continue/ssiap-1-formation-initiale[ssiap-1 formation initiale] +
link:https://www.cnaps.interieur.gouv.fr/[cnaps]

== 3) Public

être apte physiquement, cette aptitude étant attestée par un certificat médical datant de moins de trois mois, conformément à l'annexe VII de l'arrêté du 02 mai 2005.
Effectif entre 10 et 20 apprenants

== 4) Objectifs pédagogiques

// listes des compétences par domaines de compétence

.Missions de l’agent SSIAP1
* La prévention des incendies
* La sensibilisation des employés en matière de sécurité contre l’incendie, et d’assistance à personnes
* L’entretien élémentaire des moyens concourant à la sécurité incendie
* L’alerte et l’accueil des secours
* L’évacuation du public
* L’intervention précoce fasse aux incendies
* L’assistance à personnes au sein des établissements ou ils exercent
* L’exploitation du PC de sécurité incendie

== 5) Compétences visés(objectifs opérationnels)

* Effectuer l'entretien et et les vérifications élémentaires des installations et équipements de sécurité
* Appliquer des consignes de sécurité
* Lire et manipuler des tableaux de signalisation
* Effectuer des rondes de sécurité et surveillance des travaux
* Assurer la surveillance au PC
* Passer des appels et réceptionner les services publics de secours
* Pratiquer le secours à victimes
* Porter assistance à personnes
* Mettre en œuvre des moyens de secours et de mise en sécurité

== 6) Durée/Temporisation

Durée de la formation : 70 heures + examen

.Deux formules possibles:
* présentiel complet (9h/12-13h/17h)
* hybridation présentiel/distanciel (9h/12-13h/17h)


== 7) Moyen d’accompagnement/Suivis pédagogique

les acteurs donnes leurs coordonnées, qui fait quoi
